const videos = [
	{
		videoId: "BI1o2H9z9fo",
		title: "Modern JavaScript From The Beginning | First 12 Hours",
		description:
			"This is the first 12 hours of my 37-hour JavaScript course. In thes video we will go over the fundamentals in-depth.",
		creator: "Traversy Media",
		views: "278K",
		duration: "11:53:59",
		categoryName: "JavaScript",
		published: "3 months ago",
	},
	{
		videoId: "PxNDgI8SD3U",
		title: "Variables in JavaScript | JavaScript for Beginners (#4)",
		description:
			"In this video, you will learn what variables are in programming, how they work behind the scenes, and how to define a variable in JavaScript. ",
		creator: "Coding with Estefania",
		views: "58",
		duration: "4:43",
		categoryName: "JavaScript",
		published: "18 hours ago",
	},
	{
		videoId: "r9I4DuGmJ2Y",
		title: "Making a Game in JavaScript with No Experience",
		description:
			"What do Capybaras and JavaScript have in common? Well, this video! Today, I'll play the role of a full stack developer and create my first game in JavaScript with no experience.",
		creator: "Goodgis",
		views: "114K",
		duration: "1:05",
		categoryName: "JavaScript",
		published: "4 days ago",
	},
	{
		videoId: "htznIeWKgg8",
		title: "JavaScript Crash Course: Master the Basics in One Video! Ignite Your Front-End Mastery Series!",
		description:
			"Unleash your front-end development potential with our JavaScript Essentials crash course! In this action-packed series, you'll master the basics of JavaScript in one video.",
		creator: "Sheryians Coding School",
		views: "436K",
		duration: "1:13:17",
		categoryName: "JavaScript",
		published: "4 months ago",
	},
	{
		videoId: "lkIFF4maKMU",
		title: "100+ JavaScript Concepts you Need to Know",
		description:
			"The ultimate 10 minute JavaScript course that quickly breaks down over 100 key concepts every web developer should know. Learn the basics of JS and start building apps on the web, mobile, desktop, and more.",
		creator: "Fireship",
		views: "1.4M",
		duration: "12:23",
		categoryName: "JavaScript",
		published: "11 months ago",
	},
	{
		videoId: "sscX432bMZo",
		title: "Javascript in 1 shot in Hindi",
		description: "Javascript in 1 shot in Hindi | Chai aur Code",
		creator: "Chai aur Code",
		views: "269K",
		duration: "9:02:20",
		categoryName: "JavaScript",
		published: "2 months ago",
	},
	{
		videoId: "8dWL3wF_OMw",
		title: "JavaScript Full Course for free 🌐",
		description: "JavaScript tutorial for beginners full course",
		creator: "Bro Code",
		views: "2.2M",
		duration: "8:00:00",
		categoryName: "JavaScript",
		published: "6 months ago",
	},
	{
		videoId: "91btr-Gp-tI",
		title: "How to build Node.js + MongoDB with TypeScript",
		description: "How to build Node.js + MongoDB with TypeScript",
		creator: "Rui Wang",
		views: "2.3K",
		duration: "24:53",
		categoryName: "TypeScript",
		published: "7 months ago",
	},
	{
		videoId: "lfm_Hu0hEms",
		title: "Creating a Powerful E-Commerce Search and Filtering System with React",
		description:
			"In today's digital age, e-commerce websites are becoming increasingly popular, and customers demand more personalized experiences than ever before.",
		creator: "HuXn WebDev",
		views: "88K",
		duration: "1:50:13",
		categoryName: "TypeScript",
		published: "5 months ago",
	},
	{
		videoId: "02qV2icZahk",
		title: "Node & React Redux Tool Kit with Typescript",
		description: "IMPORTANT! check frontend githug repo for better CSS for the GamePage",
		creator: "Arturo Filio Villa",
		views: "11K",
		duration: "1:44:12",
		categoryName: "TypeScript",
		published: "1 year ago",
	},
	{
		videoId: "WBPrJSw7yQA",
		title: "Learn TypeScript in 50 Minutes - Tutorial for Beginners",
		description:
			"TypeScript is an open-source programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript, and adds optional static typing to the language.",
		creator: "Codevolution",
		views: "818K",
		duration: "48:10",
		categoryName: "TypeScript",
		published: "5 years ago",
	},
	{
		videoId: "5ChkQKUzDCs",
		title: "Big projects are ditching TypeScript… why?",
		description:
			"Why are some big open-source projects like Turbo and Svelte dropping TypeScript in favor of vanilla JavaScript? Learn about the pros and cons of TypeScript",
		creator: "Fireship",
		views: "931K",
		duration: "3:37",
		categoryName: "TypeScript",
		published: "1 months ago",
	},
	{
		videoId: "zQnBQ4tB3ZA",
		title: "TypeScript in 100 Seconds?",
		description:
			"Learn the basics if TypeScript in 100 Seconds! If you love TS, upgrade to Fireship PRO for 40% off using code mbus5Kcj at ",
		creator: "Fireship",
		views: "711K",
		duration: "2:24",
		categoryName: "TypeScript",
		published: "2 years ago",
	},
	{
		videoId: "1jMJDbq7ZX4",
		title: "TypeScript Course In ReactJS - TypeScript",
		description:
			"In this video I will go over everything I thing a beginner should learn on how to use Typescript in React.",
		creator: "PedroTech",
		views: "97K",
		duration: "43:04",
		categoryName: "TypeScript",
		published: "2 years ago",
	},
	{
		videoId: "W2BBskCCk8o",
		title: "My Problem with Using TypeScript in 2023",
		description: "TypeScript should be easier!",
		creator: "James Q Quick",
		views: "8.1K",
		duration: "8:14",
		categoryName: "TypeScript",
		published: "9 days ago",
	},
	{
		videoId: "SqcY0GlETPk",
		title: "React Tutorial for Beginners",
		description:
			"React JS Tutorial for Beginners - Learn React 18 with TypeScript and build awesome frontend app!",
		creator: "Programming with Mosh",
		views: "1.4M",
		duration: "1:20:03",
		categoryName: "React",
		published: "7 months ago",
	},
	{
		videoId: "Rh3tobg7hEo",
		title: "Learn React With This One Project",
		description:
			"Learning React is hard. There are so many concepts to learn and mindsets shifts that you need to do.",
		creator: "Web Dev Simplified",
		views: "453K",
		duration: "42:37",
		categoryName: "React",
		published: "6 months ago",
	},
	{
		videoId: "pfV3fOyOG5Y",
		title: "React Roadmap for High Paying Jobs for Web developer in 2023 | Tanay Pratap Hindi",
		description:
			"In this video, discover advanced techniques to elevate your frontend React project and unlock high-paying web developer jobs in 2023.",
		creator: "Tanay Pratap",
		views: "46K",
		duration: "9:42",
		categoryName: "React",
		published: "3 months ago",
	},
	{
		videoId: "HxxN6AdEop0",
		title: "🚀 Mastering React/Next.js in 90 Minutes! Advanced Techniques👩‍💻",
		description:
			"In this 90-minute deep dive, we'll take your React/Next.js skills to the next level! Building upon the foundation we laid in our previous video",
		creator: "Tanay Pratap",
		views: "60K",
		duration: "1:36:16",
		categoryName: "React",
		published: "1 months ago",
	},
	{
		videoId: "qySZIzZvZOY",
		title: "React Hooks Tutorial - 27 - useMemo Hook",
		description: "React Hooks Tutorial - 27 - useMemo Hook",
		creator: "Codeevolution",
		views: "198K",
		duration: "10:40",
		categoryName: "React",
		published: "4 months ago",
	},
	{
		videoId: "N4yUiQiTvwU",
		title: "React Proxy | Easiest Fix to CORS Errors",
		description:
			"Proxying API Requests in Development using Vite, Parcel, or Create React App. If your plan is to host your react app from the same origin as your web server, then this is super helpful. Conveniently, this also avoids CORS issues.",
		creator: "Sam Meech-Ward",
		views: "49K",
		duration: "15:51",
		categoryName: "React",
		published: "1 year ago",
	},
];

export default videos;
